### ISSUE TITLE
No Issue, Just Thanks for putting this together

### ISSUE THREAD

**Issue by jax7778** [jblaine/solarized-and-modern-putty#6]
I used this for years and recommended it to my colleagues that are stuck using putty, but realized I never thanked the person that put it together. It may not seem like much, but having solarized dark and modern sane putty settings together in a pre-made registry file is just nice.  While these settings could be put together manually, I might never have found that blog post from 2012 with sane putty settings. 

Thank you for putting it together and putting it online for everyone.

**Comment by jblaine** [comment]
Thanks for taking time to say that! You're welcome.
